
name = "Pollon"
tilemap = layer_tilemap_get_id("Collision");
hp = 1
hp_max = hp
atk = 100
m_atk = 5
def = 10
_precision = 100
mp = 25
mp_max = mp
_speed = 2
luck = 1
level = 1
xp = 0
xp_required = 100
alarm[0] = 25
target_x = obj_player2.x;
target_y = obj_player2.y;
movement_h = target_x-x
movement_v = target_y - y
follow_index = 2
position_history = ds_list_create();
history_length = 30
leader_is_moving = false;
hor = 0
ver = 0
move_speed = 1;