_turn = 0 //da 0 a 4, 4 è il turno dei nemici
_round = 1 // da 1 a infinito, indica il numero di round in totale
damage_to_enemy = 0
enemy_damage = 0
enemy_num = 0
j = 0
i = j + 4
count = -1
players = [obj_battle_player1,obj_battle_player2,obj_battle_player3,obj_battle_player4]
enemies = []
order_players = []
targets = array_create(4)
player_alive = 4
holding = false
alarm[11] = 1
