data = noone
_action = noone
_target = noone
_self = self
current_atk = data.atk
current_def = data.def
current_speed = data._speed
current_luck = data.luck
current_matk = data.m_atk
//condizione di stato
_state = noone